import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecomerce-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl bg-slate-500 font-bold underline">
        Hello world!
      </h1>
    </div>
  );
}
